{{- range $name, $component := .Values.components }}
{{- if and $component.enabled $component.secretEnv (not $component.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "freeflow.componentFullname" (list $ $name) }}
  labels:
    app.kubernetes.io/name: {{ include "freeflow.name" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/component: {{ $name }}
type: Opaque
stringData:
  {{- range $key, $value := $component.secretEnv }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
---
{{- end }}
{{- end }}
