{{- range $name, $component := .Values.components }}
{{- if and $component.enabled $component.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "freeflow.componentFullname" (list $ $name) }}
  labels:
    app.kubernetes.io/name: {{ include "freeflow.name" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/component: {{ $name }}
  {{- with $component.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
{{- end }}
{{- end }}
